version: '2'

services:
  web_app:
    image: web_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000
    volumes:
      - ./cime_mirror_engine:/app

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - web_app
