version: '2'

services:
  web_app:
    image: web_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000
    volumes:
      - ./cime_mirror_engine:/app
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - web_app
  
  postgres:
    image: arm32v7/postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=cime
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
